/* eslint-disable */
/**
 * AUTOGENERATED — DO NOT EDIT BY HAND.
 *
 * Source:    contracts/content.schema.json
 * Generator: scripts/gen-content-types.ts  (npm run gen:types)
 *
 * Edit the schema, then re-run `npm run gen:types`. `npm run build` does this
 * for you via `prebuild`.
 */

/**
 * This interface was referenced by `CaesarSiteContent`'s JSON-Schema
 * via the `definition` "sectionType".
 */
export type SectionType =
  | 'hero'
  | 'intro'
  | 'services'
  | 'stats'
  | 'showcase'
  | 'coverage'
  | 'process'
  | 'testimonials'
  | 'faq'
  | 'cta'
  | 'contact';
/**
 * This interface was referenced by `CaesarSiteContent`'s JSON-Schema
 * via the `definition` "media".
 */
export type Media = {
  id: string;
  kind: 'image' | 'video';
  /**
   * Required on every asset. Hebrew, describing the image for screen readers.
   */
  alt: string;
  /**
   * public/media/{section-id}/{variant}.{ext} per contracts/assets.md. Absent until the asset exists.
   */
  src?: string;
  /**
   * Required when kind is video.
   */
  poster?: string;
  /**
   * Where the asset came from. 'placeholder' must not survive to production.
   */
  origin?: 'kling' | 'original-site' | 'placeholder';
  credit?: string;
};
/**
 * This interface was referenced by `CaesarSiteContent`'s JSON-Schema
 * via the `definition` "provenance".
 */
export type Provenance = {
  /**
   * harvested = the company's own words, verbatim. rewritten = their words, edited for length or repetition. authored = written by Claude because coverage was thin.
   */
  source: 'harvested' | 'authored' | 'rewritten';
  /**
   * Required for harvested and rewritten. Where the copy came from.
   */
  sourceUrl?: string;
  note?: string;
};
/**
 * This interface was referenced by `CaesarSiteContent`'s JSON-Schema
 * via the `definition` "motionPreset".
 */
export type MotionPreset =
  'fade-up' | 'pin-reveal' | 'parallax-slow' | 'text-split' | 'horizontal-scroll' | 'none';

export interface CaesarSiteContent {
  site: {
    name: string;
    locale: 'he-IL';
    dir: 'rtl';
    sourceUrl: string;
    tagline: string;
    description: string;
    contact?: {
      phones?: string[];
      emails?: string[];
      address?: string;
      social?: {
        platform: string;
        href: string;
      }[];
    };
  };
  /**
   * @minItems 1
   */
  pages: [Page, ...Page[]];
}
/**
 * This interface was referenced by `CaesarSiteContent`'s JSON-Schema
 * via the `definition` "page".
 */
export interface Page {
  slug: string;
  title: string;
  metaDescription: string;
  /**
   * @minItems 1
   */
  sections: [Section, ...Section[]];
}
/**
 * This interface was referenced by `CaesarSiteContent`'s JSON-Schema
 * via the `definition` "section".
 */
export interface Section {
  /**
   * kebab-case; also the media directory name under public/media/
   */
  id: string;
  type: SectionType;
  order: number;
  heading: string;
  subheading?: string;
  /**
   * May be empty for sections that carry all their copy in items[].
   */
  body: string;
  /**
   * Repeated content: service cards, city list, stats, testimonials, FAQ rows.
   */
  items?: Item[];
  media: Media[];
  cta?: Cta;
  motion?: MotionPreset;
  provenance: Provenance;
}
/**
 * This interface was referenced by `CaesarSiteContent`'s JSON-Schema
 * via the `definition` "item".
 */
export interface Item {
  id: string;
  title: string;
  body?: string;
  /**
   * Stat figure, e.g. '10+'.
   */
  value?: string;
  /**
   * Testimonial author.
   */
  attribution?: string;
  location?: string;
  href?: string;
  media?: Media;
  provenance?: Provenance;
}
/**
 * This interface was referenced by `CaesarSiteContent`'s JSON-Schema
 * via the `definition` "cta".
 */
export interface Cta {
  label: string;
  href: string;
  style?: 'primary' | 'secondary' | 'ghost';
}

/** Root type of content/pages.json. Alias for the schema's title-derived name. */
export type SiteContent = CaesarSiteContent;
