/**
 * CONTRACT — frozen in Phase 0. The seam between `caesar-photo` and `caesar-ui`.
 *
 * The `assets` record below is REGENERATED by `npm run images:generate` once real
 * Kling output lands. `caesar-ui` must reference images by slug through
 * `getMedia()` and never hardcode a path — that is what lets the UI agent build
 * every page before a single image exists.
 *
 * Kling result URLs expire, so nothing here ever points at a Kling-hosted URL:
 * the pipeline downloads, optimises and commits local files.
 */

export type MediaAspect = '16:9' | '4:3' | '1:1' | '3:4' | '21:9';

export type MediaAsset = {
  slug: string;
  /** Hebrew, hand-authored. Never model-generated, never keyword-stuffed. */
  alt: string;
  aspect: MediaAspect;
  /** Optimised AVIF. */
  src: string;
  /** WebP fallback for browsers without AVIF. */
  fallback: string;
  /** Inline base64 LQIP shown while the real image decodes. */
  placeholder: string;
  /** object-position as [x%, y%] when the subject is off-centre. */
  focal?: [number, number];
  /**
   * True for anything Kling produced.
   *
   * Editorial and atmospheric imagery may be AI-generated. Photography of a
   * specific marketed property may NOT — publishing a synthetic image of a real
   * listing is misleading and carries consumer-protection exposure in Israel.
   * This flag keeps that auditable: listing galleries assert `aiGenerated: false`.
   */
  aiGenerated: boolean;
};

/** Neutral tone block, so an unfulfilled slug degrades quietly instead of breaking layout. */
const PLACEHOLDER_PIXEL =
  'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0IDMiPjxyZWN0IHdpZHRoPSI0IiBoZWlnaHQ9IjMiIGZpbGw9IiNFN0U0REQiLz48L3N2Zz4=';

/**
 * Generated block. Everything below is rewritten by the image pipeline.
 * Hand edits here will be overwritten — change the manifest instead.
 */
export const assets: Record<string, MediaAsset> = {};

/**
 * Resolve a slug to an asset, falling back to a neutral placeholder.
 *
 * Deliberately total: the UI agent works against slugs that do not exist yet, so
 * a missing image is a normal intermediate state, not an error.
 */
export function getMedia(slug: string, aspect: MediaAspect = '4:3'): MediaAsset {
  const asset = assets[slug];
  if (asset) return asset;

  return {
    slug,
    alt: '',
    aspect,
    src: PLACEHOLDER_PIXEL,
    fallback: PLACEHOLDER_PIXEL,
    placeholder: PLACEHOLDER_PIXEL,
    aiGenerated: false,
  };
}

/** True once the pipeline has produced a real file for this slug. */
export function hasMedia(slug: string): boolean {
  return slug in assets;
}

/** Tailwind aspect-ratio classes, so callers reserve space and avoid layout shift. */
export const aspectClass: Record<MediaAspect, string> = {
  '16:9': 'aspect-[16/9]',
  '4:3': 'aspect-[4/3]',
  '1:1': 'aspect-square',
  '3:4': 'aspect-[3/4]',
  '21:9': 'aspect-[21/9]',
};
