import { parseAll, postSchema, type Post } from './types';

/**
 * The blog ("פוסטים אחרונים") and news ("חדשות קיסר") archives, as listed on
 * the client's homepage.
 *
 * WHAT WE ACTUALLY HAVE. The homepage lists each post's title, its thumbnail and
 * its permalink. It does not print publication dates, and it does not print
 * teasers. Only the homepage could be read, so that is the whole of it. Every
 * record here is therefore `needsReview: true`, and two fields are conventions
 * rather than data:
 *
 *   `publishedAt` is `PENDING_DATE`, a deliberately impossible sentinel. It is
 *   not a guess dressed up as a date. Nothing may present it to a reader:
 *   use `hasRealDate()` before rendering one, and sort the archive by array
 *   order (the client's own newest-first ordering) until the real dates arrive.
 *
 *   `excerpt` repeats the title wherever no teaser exists. `hasRealExcerpt()`
 *   says whether a record has a distinct one; none does yet. Writing invented
 *   teasers for a hundred posts we have not read would put words in the
 *   client's mouth a hundred times over.
 *
 * TITLES ARE TRIMMED, NOT REWRITTEN. Legacy titles piled several keyword
 * phrases into one string separated by pipes — "ניהול נכסים בירושלים | ניהול
 * נכסים ללא תשלום | אחזקת מבנים בירושלים | חברה לניהול נכסים בירושלים | …".
 * `title` keeps the first phrase, which is the client's own wording, and drops
 * the pile. Nothing is added.
 *
 * A NOTE FOR THE CONTENT REVIEW. The archive contains long runs of near-identical
 * city posts (five separate "ניהול נכסים בתל אביב" posts, two for בת ים, two for
 * ראשון לציון, three on ניהול מרכזים מסחריים). The slugs below disambiguate them
 * with a numeric suffix so every legacy URL still resolves, but these are
 * doorway pages and the right long-term fix is to consolidate each cluster into
 * one real page and point the rest at it. That is a decision for the client.
 *
 * Four posts appear in both the blog carousel and the news carousel; they are
 * recorded once, as news, since that is the more specific category.
 *
 * `/רוצה-לדעת-כמה-הדירה-שלך-שווה/` also appears in the news carousel but is the
 * valuation service page; it is handled in `services.ts`, not here.
 */

/**
 * Sentinel for "we do not know when this was published".
 *
 * Chosen to be obviously wrong rather than plausibly right: the site is a
 * 2015-era WordPress build, so nothing on it was published in 1900. A plausible
 * fake date would quietly become a fact.
 */
export const PENDING_DATE = '1900-01-01';

export const posts: Post[] = parseAll(
  postSchema,
  [
    {
      slug: 'שרות-חדש',
      kind: 'news',
      title: 'שרות חדש! שיפוץ עיצוב אדריכלי ושדרוג הבית בכל תקציב',
      excerpt: 'שרות חדש! שיפוץ עיצוב אדריכלי ושדרוג הבית בכל תקציב',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/שרות-חדש-שיפוץ-עיצוב-אדריכלי-ושדרוג-הב/'],
      needsReview: true,
    },
    {
      slug: 'להיות-זכיינים',
      kind: 'news',
      title: 'להיות זכיינים, זכיין ברשת נדל"ן, מתווכים, ניהול נכסים',
      excerpt: 'להיות זכיינים, זכיין ברשת נדל"ן, מתווכים, ניהול נכסים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/איזה-רשת-זכיינים-מציעה-לך-להיות-זכיין-ע/'],
      needsReview: true,
    },
    {
      slug: 'אזורי-שירות',
      kind: 'news',
      title: 'אזורי שירות, ניהול נכסים, ניהול דירות',
      excerpt: 'אזורי שירות, ניהול נכסים, ניהול דירות',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/אזורי-שירות-ניהול-נכסים-ניהול-דירות/'],
      needsReview: true,
    },
    {
      slug: 'קיסר-ניהול-נכסים-בירושלים-מנהלת-את',
      kind: 'news',
      title: 'קיסר ניהול נכסים בירושלים מנהלת את כל סוגי הנכסים בירושלים',
      excerpt: 'קיסר ניהול נכסים בירושלים מנהלת את כל סוגי הנכסים בירושלים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/קיסר-ניהול-נכסים-בירושלים-מנהלת-נכסים/'],
      needsReview: true,
    },
    {
      slug: 'חברה-מומלצת-לניהול-נכסים-ודירות',
      kind: 'news',
      title: 'חברה מומלצת לניהול נכסים ודירות? נכון אין כמו קיסר',
      excerpt: 'חברה מומלצת לניהול נכסים ודירות? נכון אין כמו קיסר',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/חברה-מומלצת-לניהול-נכסים-ודירות-נכון-א/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בתל-אביב',
      kind: 'news',
      title: 'ניהול נכסים בתל אביב: חדש לבעלי דירות בתל אביב',
      excerpt: 'ניהול נכסים בתל אביב: חדש לבעלי דירות בתל אביב',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בתל-אביב-חדש-לבעלי-דירות-בת/'],
      needsReview: true,
    },
    {
      slug: 'פרופסור-שבח-וייס-הצטרף-לחוג-הלקוחות',
      kind: 'news',
      title: 'פרופסור שבח וייס הצטרף לחוג הלקוחות של קיסר ניהול נכסים בחיפה, מזל טוב!',
      excerpt: 'פרופסור שבח וייס הצטרף לחוג הלקוחות של קיסר ניהול נכסים בחיפה, מזל טוב!',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/פרופסור-שבח-וייס-יור-הכנסת-לשעבר-הצטר/'],
      needsReview: true,
    },
    {
      slug: 'חדש-בקיסר-ניהול-נכסים-הלוואות',
      kind: 'news',
      title: 'חדש בקיסר ניהול נכסים – הלוואות, אשראי חוץ בנקאי למימון שכ"ד בתנאים מעולים!',
      excerpt: 'חדש בקיסר ניהול נכסים – הלוואות, אשראי חוץ בנקאי למימון שכ"ד בתנאים מעולים!',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/חדש-בקיסר-אשראי-חוץ-בנקאי-למימון-שכד-ב/'],
      needsReview: true,
    },
    {
      slug: 'בית-מלון-בקו-הים-מחפש-משקיע',
      kind: 'news',
      title: 'בית מלון בקו הים – מחפש משקיע אם אופק רחב',
      excerpt: 'בית מלון בקו הים – מחפש משקיע אם אופק רחב',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/מלון-דירות-בקו-הים-מחפש-משקיע-עם-אופק-רח/'],
      needsReview: true,
    },
    {
      slug: 'קיסר-ניהול-נכסים-בחיפה-מברכת-את',
      kind: 'news',
      title: 'קיסר ניהול נכסים בחיפה מברכת את עו"ד גיתאי ברלל שבחר בנו לניהול דירותיו בחיפה',
      excerpt: 'קיסר ניהול נכסים בחיפה מברכת את עו"ד גיתאי ברלל שבחר בנו לניהול דירותיו בחיפה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-מברכת-את-עוד-גיתאי-ברלל-שב/'],
      needsReview: true,
    },
    {
      slug: 'חדש-ניהול-תיק-השקעות',
      kind: 'news',
      title:
        'חדש ניהול תיק השקעות, דירות להשקעה וניהול נכסים – החבילה המושלמת למשקיעים שחפצים בדירה להשקעה',
      excerpt:
        'חדש ניהול תיק השקעות, דירות להשקעה וניהול נכסים – החבילה המושלמת למשקיעים שחפצים בדירה להשקעה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/חדש-ניהול-תיק-השקעות-מבוסס-נדלן-וניהול-2/'],
      needsReview: true,
    },
    {
      slug: 'רוצים-לקבל-את-הטיפים-והנכסים-להשקעה',
      kind: 'news',
      title: 'רוצים לקבל את הטיפים והנכסים להשקעה הכי חמים באון ליין',
      excerpt: 'רוצים לקבל את הטיפים והנכסים להשקעה הכי חמים באון ליין',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/רוצים-לקבל-את-הטיפים-והנכסים-להשקעה-הכ/'],
      needsReview: true,
    },
    {
      slug: 'הצטרפו-למועדון-המשקיעים-העולמי-שלנו-כמשקיע',
      kind: 'news',
      title: 'הצטרפו למועדון המשקיעים העולמי שלנו כמשקיע או כמנטור',
      excerpt: 'הצטרפו למועדון המשקיעים העולמי שלנו כמשקיע או כמנטור',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/הצטרפו-למועדון-המשקיעים-העולמי-שלנו-כ/'],
      needsReview: true,
    },
    {
      slug: 'שיווק-פרויקטים-חדשים',
      kind: 'blog',
      title: 'שיווק פרויקטים חדשים, למה לשים לב שקונים דירה מקבלן',
      excerpt: 'שיווק פרויקטים חדשים, למה לשים לב שקונים דירה מקבלן',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/שיווק-פרויקטים-חדשים-למה-לשים-לב-שקוני/'],
      needsReview: true,
    },
    {
      slug: 'כיצד-לנהל-את-הנכסים-והדירות-שלך',
      kind: 'blog',
      title: 'כיצד לנהל את הנכסים והדירות שלך בתל אביב בצורה מיטבית',
      excerpt: 'כיצד לנהל את הנכסים והדירות שלך בתל אביב בצורה מיטבית',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/כיצד-לנהל-את-הנכסים-והדירות-שלך-בתל-אבי/'],
      needsReview: true,
    },
    {
      slug: 'כיצד-לנהל-נכסים-ודירות-בצורה-מיטבית',
      kind: 'blog',
      title: 'כיצד לנהל נכסים ודירות בצורה מיטבית',
      excerpt: 'כיצד לנהל נכסים ודירות בצורה מיטבית',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/כיצד-לנהל-נכסים-ודירות-בצורה-מיטבית/'],
      needsReview: true,
    },
    {
      slug: 'מדריך-מקיף-לניהול-נכסים-בתל-אביב',
      kind: 'blog',
      title: 'מדריך מקיף לניהול נכסים בתל אביב',
      excerpt: 'מדריך מקיף לניהול נכסים בתל אביב',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/מדריך-מקיף-לניהול-נכסים-בתל-אביב/'],
      needsReview: true,
    },
    {
      slug: 'כיצד-להצליח-בניהול-נכסים',
      kind: 'blog',
      title: 'כיצד להצליח בניהול נכסים: עקרונות וטיפים לניהול נכסים בישראל',
      excerpt: 'כיצד להצליח בניהול נכסים: עקרונות וטיפים לניהול נכסים בישראל',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/כיצד-להצליח-בניהול-נכסים-עקרונות-וטיפ/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-ושיווק-נכסים',
      kind: 'blog',
      title: 'ניהול נכסים ושיווק נכסים',
      excerpt: 'ניהול נכסים ושיווק נכסים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-ושיווק-נכסים/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-מתחמי-מגורים-דיור-ונופש',
      kind: 'blog',
      title: 'ניהול נכסים מתחמי מגורים דיור ונופש',
      excerpt: 'ניהול נכסים מתחמי מגורים דיור ונופש',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-מתחמי-מגורים-דיור-ונופש/'],
      needsReview: true,
    },
    {
      slug: 'מה-פירוש-המילה-ניהול-נכסים-ואחזקה',
      kind: 'blog',
      title: 'מה פירוש המילה ניהול נכסים ואחזקה ?',
      excerpt: 'מה פירוש המילה ניהול נכסים ואחזקה ?',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/מה-פירוש-המילה-ניהול-נכסים-ואחזקה/'],
      needsReview: true,
    },
    {
      slug: 'מומחים-ניהול-נכסים-חברה-לניהול-נכסים',
      kind: 'blog',
      title: 'מומחים ניהול נכסים – חברה לניהול נכסים בישראל',
      excerpt: 'מומחים ניהול נכסים – חברה לניהול נכסים בישראל',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/מומחים-ניהול-נכסים-חברה-לניהול-נכסים-ב/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-מומחים-לניהול-נכסים-החברה',
      kind: 'blog',
      title: 'ניהול נכסים – מומחים לניהול נכסים החברה המובילה',
      excerpt: 'ניהול נכסים – מומחים לניהול נכסים החברה המובילה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-מומחים-לניהול-נכסים-החברה/'],
      needsReview: true,
    },
    {
      slug: 'חברה-לניהול-נכסים-ללא-עמלות-ודמי',
      kind: 'blog',
      title: 'חברה לניהול נכסים ללא עמלות ודמי ניהול',
      excerpt: 'חברה לניהול נכסים ללא עמלות ודמי ניהול',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/חברה-לניהול-נכסים-ללא-עמלות-ודמי-ניהול/'],
      needsReview: true,
    },
    {
      slug: 'אחזקה-וניהול-נכסים',
      kind: 'blog',
      title: 'אחזקה וניהול נכסים: טובים השניים מין האחד',
      excerpt: 'אחזקה וניהול נכסים: טובים השניים מין האחד',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/אחזקה-וניהול-נכסים-טובים-השניים-מין-הא/'],
      needsReview: true,
    },
    {
      slug: 'חברת-ניהול-נכסים-ואחזקת-מבנים-שחייבים',
      kind: 'blog',
      title: 'חברת ניהול נכסים ואחזקת מבנים שחייבים להכיר!',
      excerpt: 'חברת ניהול נכסים ואחזקת מבנים שחייבים להכיר!',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-ואחזקת-מבנים-שחייבים-להכי/'],
      needsReview: true,
    },
    {
      slug: 'שיווק-וניהול-נכסים-ושטחים-מסחריים',
      kind: 'blog',
      title: 'שיווק וניהול נכסים ושטחים מסחריים',
      excerpt: 'שיווק וניהול נכסים ושטחים מסחריים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/שיווק-וניהול-נכסים-ושטחים-מסחריים/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-קניונים-אפשר-ליזום-בשקט',
      kind: 'blog',
      title: 'ניהול קניונים – אפשר ליזום בשקט',
      excerpt: 'ניהול קניונים – אפשר ליזום בשקט',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-קניונים-אפשר-ליזום-בשקט/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-במודיעין-וביישובי-הסביבה',
      kind: 'blog',
      title: 'ניהול נכסים במודיעין וביישובי הסביבה',
      excerpt: 'ניהול נכסים במודיעין וביישובי הסביבה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-במודיעין-וביישובי-הסביבה/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בקריית-אונו-ניהול-הנכס',
      kind: 'blog',
      title: 'ניהול נכסים בקריית אונו – ניהול הנכס ללא תשלום?',
      excerpt: 'ניהול נכסים בקריית אונו – ניהול הנכס ללא תשלום?',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בקריית-אונו-ניהול-הנכס-ל/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בחדרה-בשיטה-המושלמת',
      kind: 'blog',
      title: 'ניהול נכסים בחדרה – בשיטה המושלמת',
      excerpt: 'ניהול נכסים בחדרה – בשיטה המושלמת',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בחדרה-בשיטה-המושלמת/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-ברמת-השרון-ובמגורי-יוקרה',
      kind: 'blog',
      title: 'ניהול נכסים ברמת השרון ובמגורי יוקרה',
      excerpt: 'ניהול נכסים ברמת השרון ובמגורי יוקרה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-ברמת-השרון-ובמגורי-יוקרה/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בחיפה',
      kind: 'blog',
      title: 'ניהול נכסים בחיפה',
      excerpt: 'ניהול נכסים בחיפה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בחיפה-ניהול-דירות-להשקעה-ב/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בראשון-לציון-ללא-תשלום',
      kind: 'blog',
      title: 'ניהול נכסים בראשון לציון ללא תשלום',
      excerpt: 'ניהול נכסים בראשון לציון ללא תשלום',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בראשון-לציון-2/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-מניבים-לבעלי-נכסים-שאוהבים',
      kind: 'blog',
      title: 'ניהול נכסים מניבים לבעלי נכסים שאוהבים ראש שקט',
      excerpt: 'ניהול נכסים מניבים לבעלי נכסים שאוהבים ראש שקט',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-מניבים-לבעלי-נכסים-שאוהבי/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-מרכזים-מסחריים',
      kind: 'blog',
      title: 'ניהול מרכזים מסחריים',
      excerpt: 'ניהול מרכזים מסחריים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-קניונים/'],
      needsReview: true,
    },
    {
      slug: 'שיווק-וניהול-נכסים',
      kind: 'blog',
      title: 'שיווק וניהול נכסים',
      excerpt: 'שיווק וניהול נכסים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/שיווק-וניהול-נכסים-ניהול-נכסים-מניבים/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בכפר-סבא',
      kind: 'blog',
      title: 'ניהול נכסים בכפר סבא',
      excerpt: 'ניהול נכסים בכפר סבא',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בכפר-סבא/'],
      needsReview: true,
    },
    {
      slug: 'נכסים-מניבים-לך-יותר-בשיטת-המושלמת',
      kind: 'blog',
      title: 'נכסים מניבים לך יותר – בשיטת המושלמת',
      excerpt: 'נכסים מניבים לך יותר – בשיטת המושלמת',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/נכסים-מניבים-לך-יותר-בשיטת-המושלמת/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-ואחזקת-מבנים-מכל-הסוגים-מידי',
      kind: 'blog',
      title: 'ניהול ואחזקת מבנים מכל הסוגים מידי המומחים של קיסר',
      excerpt: 'ניהול ואחזקת מבנים מכל הסוגים מידי המומחים של קיסר',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-ואחזקת-מבנים-מכל-הסוגים-מידי-המו/'],
      needsReview: true,
    },
    {
      slug: 'אחזקת-מבנים-כל-השאלות-שלא-חשבת',
      kind: 'blog',
      title: 'אחזקת מבנים – כל השאלות שלא חשבת לשאול',
      excerpt: 'אחזקת מבנים – כל השאלות שלא חשבת לשאול',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/אחזקת-מבנים-כל-השאלות-שלא-חשבת-לשאול/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-קניונים-ומרכזי-קניות',
      kind: 'blog',
      title: 'ניהול קניונים ומרכזי קניות',
      excerpt: 'ניהול קניונים ומרכזי קניות',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-קניונים-ומרכזי-קניות/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-ברעננה',
      kind: 'blog',
      title: 'ניהול נכסים ברעננה',
      excerpt: 'ניהול נכסים ברעננה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-ברעננה-החברה-המומלצת-ברענ/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בגבעתיים',
      kind: 'blog',
      title: 'ניהול נכסים בגבעתיים',
      excerpt: 'ניהול נכסים בגבעתיים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בגבעתיים-החברה-המומלצת-לנ/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בבני-ברק-בסטנדרט-גבוה',
      kind: 'blog',
      title: 'ניהול נכסים בבני ברק בסטנדרט גבוה',
      excerpt: 'ניהול נכסים בבני ברק בסטנדרט גבוה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בבני-ברק-בסטנדרט-גבוה-ניהו/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בהוד-השרון',
      kind: 'blog',
      title: 'ניהול נכסים בהוד השרון',
      excerpt: 'ניהול נכסים בהוד השרון',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בהוד-השרון-חברה-מומלצת-לני/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בבת-ים-בסטנדרט-גבוה',
      kind: 'blog',
      title: 'ניהול נכסים בבת ים בסטנדרט גבוה',
      excerpt: 'ניהול נכסים בבת ים בסטנדרט גבוה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בבת-ים-2/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בקיסריה-בסטנדרט-גבוה',
      kind: 'blog',
      title: 'ניהול נכסים בקיסריה בסטנדרט גבוה',
      excerpt: 'ניהול נכסים בקיסריה בסטנדרט גבוה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בקיסריה-בסטנדרט-גבוה-ניהו/'],
      needsReview: true,
    },
    {
      slug: 'חברה-מומלצת-ומקצועית-ל-ניהול-נכסים',
      kind: 'blog',
      title:
        'חברה מומלצת ומקצועית ל ניהול נכסים, אחזקת מבנים, ניהול קניונים, מרכזים מסחריים, נכסים מניבים, שאתם חייבים להכיר',
      excerpt:
        'חברה מומלצת ומקצועית ל ניהול נכסים, אחזקת מבנים, ניהול קניונים, מרכזים מסחריים, נכסים מניבים, שאתם חייבים להכיר',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-ואחזקת-מבנים-קניונים-מרכז/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-באשדוד',
      kind: 'blog',
      title: 'ניהול נכסים באשדוד',
      excerpt: 'ניהול נכסים באשדוד',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-באשדוד-ניהול-נכסים-ללא-תשל/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בקריות',
      kind: 'blog',
      title: 'ניהול נכסים בקריות',
      excerpt: 'ניהול נכסים בקריות',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בקריות-ניהול-נכסים-ללא-תשל-2/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בירושלים',
      kind: 'blog',
      title: 'ניהול נכסים בירושלים',
      excerpt: 'ניהול נכסים בירושלים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בירושלים-ניהול-נכסים-ללא-ת/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-מרכזים-מסחריים-2',
      kind: 'blog',
      title: 'ניהול מרכזים מסחריים',
      excerpt: 'ניהול מרכזים מסחריים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-קניונים-ניהול-מרכזים-מסחריים-נ/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בנתניה',
      kind: 'blog',
      title: 'ניהול נכסים בנתניה',
      excerpt: 'ניהול נכסים בנתניה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בנתניה-ניהול-נכסים-ללא-תשל/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בהרצליה',
      kind: 'blog',
      title: 'ניהול נכסים בהרצליה',
      excerpt: 'ניהול נכסים בהרצליה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בהרצליה-ניהול-נכסים-ללא-תש/'],
      needsReview: true,
    },
    {
      slug: 'חברות-שיווק-פרויקטים-בנדלן',
      kind: 'blog',
      title: 'חברות שיווק פרויקטים בנדל"ן',
      excerpt: 'חברות שיווק פרויקטים בנדל"ן',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/חברה-לשיווק-פרויקטים-חברות-לשיווק-פרו/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-ואחזקת-מבנים',
      kind: 'blog',
      title: 'ניהול ואחזקת מבנים',
      excerpt: 'ניהול ואחזקת מבנים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-ואחזקת-מבנים-חברה-לאחזקת-מבנים/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בחיפה-2',
      kind: 'blog',
      title: 'ניהול נכסים בחיפה',
      excerpt: 'ניהול נכסים בחיפה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בחיפה-ניהול-נכסים-ללא-תשלו/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-ברמת-גן',
      kind: 'blog',
      title: 'ניהול נכסים ברמת גן',
      excerpt: 'ניהול נכסים ברמת גן',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-ברמת-גן-ניהול-נכסים-ללא-תש/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בתל-אביב-2',
      kind: 'blog',
      title: 'ניהול נכסים בתל אביב',
      excerpt: 'ניהול נכסים בתל אביב',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בתל-אביב-ניהול-נכסים-ללא-ת/'],
      needsReview: true,
    },
    {
      slug: 'חברות-אחזקה-וניהול-מבנים',
      kind: 'blog',
      title: 'חברות אחזקה וניהול מבנים',
      excerpt: 'חברות אחזקה וניהול מבנים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/אחזקת-מבנים-חברות-אחזקה-וניהול-מבנים/'],
      needsReview: true,
    },
    {
      slug: 'חברות-לניהול-נכסים',
      kind: 'blog',
      title: 'חברות לניהול נכסים',
      excerpt: 'חברות לניהול נכסים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-חברות-לניהול-נכסים-חברה-ל/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-מרכזים-מסחריים-3',
      kind: 'blog',
      title: 'ניהול מרכזים מסחריים',
      excerpt: 'ניהול מרכזים מסחריים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-קניונים-ניהול-מרכזים-מסחריים-א/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-דירות-להשכרה-למכירה-ללא-תשלום',
      kind: 'blog',
      title: 'ניהול דירות להשכרה / למכירה ללא תשלום',
      excerpt: 'ניהול דירות להשכרה / למכירה ללא תשלום',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/עיצוב-פנים-ניהול-דירות-להשכרה-למכירה/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בתל-אביב-יפו',
      kind: 'blog',
      title: 'ניהול נכסים בתל אביב יפו',
      excerpt: 'ניהול נכסים בתל אביב יפו',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בתל-אביב-יפו-ניהול-נכסים-ל/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בפתח-תקווה',
      kind: 'blog',
      title: 'ניהול נכסים בפתח תקווה',
      excerpt: 'ניהול נכסים בפתח תקווה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בפתח-תקווה-ניהול-נכסים-ללא/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-ללא-תשלום',
      kind: 'blog',
      title: 'ניהול נכסים ללא תשלום',
      excerpt: 'ניהול נכסים ללא תשלום',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-ללא-תשלום-ניהול-דירות-שכור/'],
      needsReview: true,
    },
    {
      slug: 'השוואת-מחירים-בין-חברות-לניהול-נכסים',
      kind: 'blog',
      title: 'השוואת מחירים בין חברות לניהול נכסים',
      excerpt: 'השוואת מחירים בין חברות לניהול נכסים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/השוואת-מחירים-בין-חברות-לניהול-נכסים-ע/'],
      needsReview: true,
    },
    {
      slug: 'איך-בוחרים-חברה-לניהול-ואחזקת-מבנים',
      kind: 'blog',
      title: 'איך בוחרים חברה לניהול ואחזקת מבנים קניונים מרכזים מסחריים?',
      excerpt: 'איך בוחרים חברה לניהול ואחזקת מבנים קניונים מרכזים מסחריים?',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/איך-בוחרים-חברת-לניהול-ואחזקת-מבנים-קנ/'],
      needsReview: true,
    },
    {
      slug: 'בבעלותכם-נכסים',
      kind: 'blog',
      title: 'בבעלותכם נכסים? אתם חייבים להחליף את החברה לניהול נכסים שלכם',
      excerpt: 'בבעלותכם נכסים? אתם חייבים להחליף את החברה לניהול נכסים שלכם',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/בבעלותכם-נכסים-אתם-חייבים-להחליף-את-הח/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-ואחזקת-נכסים',
      kind: 'blog',
      title: 'ניהול ואחזקת נכסים',
      excerpt: 'ניהול ואחזקת נכסים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/היתרונות-בלקיחת-חברת-ניהול-נכסים-שתנה/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בתל-אביב-3',
      kind: 'blog',
      title: 'ניהול נכסים בתל אביב',
      excerpt: 'ניהול נכסים בתל אביב',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/חברה-מומלצת-ניהול-נכסים-אחזקת-מבנים-ונ/'],
      needsReview: true,
    },
    {
      slug: 'קיסר-ניהול-נכסים-בנתניה',
      kind: 'blog',
      title:
        'קיסר ניהול נכסים בנתניה: ניהול נכסים, דירות, מגדלים, מבנים, מרכזים שטחים, קניונים, מסחריים בנתניה',
      excerpt:
        'קיסר ניהול נכסים בנתניה: ניהול נכסים, דירות, מגדלים, מבנים, מרכזים שטחים, קניונים, מסחריים בנתניה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/קיסר-ניהול-נכסים-בנתניה-ניהול-נכסים-די/'],
      needsReview: true,
    },
    {
      slug: 'איך-בוחרים-חברה-לניהול-מגדלי-מגורים',
      kind: 'blog',
      title: 'איך בוחרים חברה לניהול מגדלי מגורים, מתחמי מגורי יוקרה?',
      excerpt: 'איך בוחרים חברה לניהול מגדלי מגורים, מתחמי מגורי יוקרה?',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/איך-בוחרים-חברה-לניהול-מגדלי-מגורים-מת/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בבני-ברק',
      kind: 'blog',
      title:
        'ניהול נכסים בבני ברק: מרכזים, מבנים, דירות, משרדים, קניונים, מגדלים, מסחריים בבני ברק',
      excerpt:
        'ניהול נכסים בבני ברק: מרכזים, מבנים, דירות, משרדים, קניונים, מגדלים, מסחריים בבני ברק',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-מרכזים-מבנים-דירות-משרדי/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בפתח-תקווה-2',
      kind: 'blog',
      title:
        'ניהול נכסים בפתח תקווה: מבנים, דירות, קניונים, מרכזים, מגדלים, שטחים מסחריים בפתח תקווה',
      excerpt:
        'ניהול נכסים בפתח תקווה: מבנים, דירות, קניונים, מרכזים, מגדלים, שטחים מסחריים בפתח תקווה',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בפתח-תקווה/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בתל-אביב-4',
      kind: 'blog',
      title: 'ניהול נכסים בתל אביב: במה שונה ניהול נכסים בתל אביב?',
      excerpt: 'ניהול נכסים בתל אביב: במה שונה ניהול נכסים בתל אביב?',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/תחום-ניהול-נכסים-בתל-אביב-במה-שונה-ניהו/'],
      needsReview: true,
    },
    {
      slug: 'חברת-אחזקות-וניהול-מבנים-מרכזים-קניונים',
      kind: 'blog',
      title: 'חברת אחזקות וניהול מבנים מרכזים קניונים מסחריים מומלצת',
      excerpt: 'חברת אחזקות וניהול מבנים מרכזים קניונים מסחריים מומלצת',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/חברות-ניהול-מבנים-מרכזים-קניונים-מסחר/'],
      needsReview: true,
    },
    {
      slug: 'זכיינות-מהי',
      kind: 'blog',
      title: 'זכיינות מהי? מהם הדברים שצריך לשים לב לפני שמצטרפים כזכיין לרשת זכיינים ?',
      excerpt: 'זכיינות מהי? מהם הדברים שצריך לשים לב לפני שמצטרפים כזכיין לרשת זכיינים ?',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/זכיינות-מהי-מהם-הדברים-שצריך-לשים-לב-לפ/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-מסחריים',
      kind: 'blog',
      title:
        'ניהול נכסים מסחריים: מדוע קניונים או מרכזים מסחריים חייבים חברת אחזקה וניהול הקניון או המרכז המסחרי',
      excerpt:
        'ניהול נכסים מסחריים: מדוע קניונים או מרכזים מסחריים חייבים חברת אחזקה וניהול הקניון או המרכז המסחרי',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/שיווק-ניהול-נכסים-מסחריים-קניונים-מרכ/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-מבנים-מסחריים',
      kind: 'blog',
      title: 'ניהול מבנים מסחריים, תפקידה של חברת ניהול נכסים בעידן המתקדם',
      excerpt: 'ניהול מבנים מסחריים, תפקידה של חברת ניהול נכסים בעידן המתקדם',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-מבנים-מסחריים-תפקידה-של-חברת-ניה/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בתל-אביב-5',
      kind: 'blog',
      title: 'ניהול נכסים בתל אביב, ניהול נכסים בהרצליה, ניהול נכסים בישראל',
      excerpt: 'ניהול נכסים בתל אביב, ניהול נכסים בהרצליה, ניהול נכסים בישראל',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בתל-אביב-ניהול-נכסים-בהרצל/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בתל-אביב-שירות-הכל',
      kind: 'blog',
      title: 'ניהול נכסים בתל אביב – שירות "הכל כלול" בתל אביב',
      excerpt: 'ניהול נכסים בתל אביב – שירות "הכל כלול" בתל אביב',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בתל-אביב-שירות-הכל-כלול-בת/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-דירות-בתל-אביב-בתא',
      kind: 'blog',
      title: 'ניהול דירות בתל אביב בת"א',
      excerpt: 'ניהול דירות בתל אביב בת"א',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-ניהול-דירות-בתל-אביב-אחלה-ש/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-שיווק-בתי-יוקרה',
      kind: 'blog',
      title: 'ניהול נכסים שיווק בתי יוקרה, דירות יוקרה, מגדלי יוקרה, מגורי יוקרה בישראל?',
      excerpt: 'ניהול נכסים שיווק בתי יוקרה, דירות יוקרה, מגדלי יוקרה, מגורי יוקרה בישראל?',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/איך-בוחרים-חברה-לניהול-שיווק-נכסי-בתי-י/'],
      needsReview: true,
    },
    {
      slug: 'איך-בוחרים-חברה-לשיווק-פרויקטים-חדשים',
      kind: 'blog',
      title: 'איך בוחרים חברה לשיווק פרויקטים חדשים למגורים?',
      excerpt: 'איך בוחרים חברה לשיווק פרויקטים חדשים למגורים?',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/איך-בוחרים-חברת-שיווק-פרויקטים-חדשים-ל/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בראשון-לציון',
      kind: 'blog',
      title: 'ניהול נכסים בראשון לציון',
      excerpt: 'ניהול נכסים בראשון לציון',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בראשון-לציון/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בבת-ים',
      kind: 'blog',
      title: 'ניהול נכסים בבת ים',
      excerpt: 'ניהול נכסים בבת ים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בבת-ים/'],
      needsReview: true,
    },
    {
      slug: 'חברה-מומלצת-לניהול-נכסים-ברמת-גן',
      kind: 'blog',
      title: 'חברה מומלצת לניהול נכסים ברמת גן וניהול דירות ברמת גן',
      excerpt: 'חברה מומלצת לניהול נכסים ברמת גן וניהול דירות ברמת גן',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-ברמת-גן-ניהול-דירות-ברמת-גן/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-בתל-אביב-זה-קיסר',
      kind: 'blog',
      title: 'ניהול נכסים בתל אביב זה קיסר אחזקות ניהול נכסים',
      excerpt: 'ניהול נכסים בתל אביב זה קיסר אחזקות ניהול נכסים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-בתל-אביב-זה-קיסר-אחזקות-ניה/'],
      needsReview: true,
    },
    {
      slug: 'דירה-להשקעה',
      kind: 'blog',
      title: 'דירה להשקעה: האם שווה לנו למכור את הדירה למגורים שלנו ולקנות דירות להשקעה?',
      excerpt: 'דירה להשקעה: האם שווה לנו למכור את הדירה למגורים שלנו ולקנות דירות להשקעה?',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/דירה-להשקעה-האם-שווה-לנו-למכור-את-הדירה/'],
      needsReview: true,
    },
    {
      slug: 'דניאל-אסייג-הבן-של-הסטנדאפיסט-שלום',
      kind: 'blog',
      title: 'דניאל אסייג הבן של הסטנדאפיסט שלום אסייג הצטרף לחוג הלקוחות של קיסר ניהול נכסים',
      excerpt: 'דניאל אסייג הבן של הסטנדאפיסט שלום אסייג הצטרף לחוג הלקוחות של קיסר ניהול נכסים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/דניאל-אסייג-הבן-של-הסטנדאפיסט-שלום-אסי/'],
      needsReview: true,
    },
    {
      slug: 'הטיפים-החשובים-למכירת-דירה-ביעילות-ומהירות',
      kind: 'blog',
      title: 'הטיפים החשובים למכירת דירה ביעילות ומהירות? ניהול נכסים',
      excerpt: 'הטיפים החשובים למכירת דירה ביעילות ומהירות? ניהול נכסים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/הטיפים-החשובים-למכירת-דירה-ביעילות-ומ/'],
      needsReview: true,
    },
    {
      slug: 'ניהול-נכסים-או-מתווכים',
      kind: 'blog',
      title: 'ניהול נכסים או מתווכים? איך בוחרים חברה לניהול נכסים?',
      excerpt: 'ניהול נכסים או מתווכים? איך בוחרים חברה לניהול נכסים?',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/ניהול-נכסים-או-מתווכים-איך-בוחרים-חברה/'],
      needsReview: true,
    },
    {
      slug: 'דירות-להשקעה-בחיפה-או-דירות-להשקעה',
      kind: 'blog',
      title: 'דירות להשקעה בחיפה או דירות להשקעה בתל אביב, מה ההבדל ?',
      excerpt: 'דירות להשקעה בחיפה או דירות להשקעה בתל אביב, מה ההבדל ?',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/דירות-להשקעה-בחיפה-או-דירות-להשקעה-בתל/'],
      needsReview: true,
    },
    {
      slug: 'קבוצות-רכישה-למה-זה-טוב-ומה',
      kind: 'blog',
      title: 'קבוצות רכישה למה זה טוב ומה הסיכונים',
      excerpt: 'קבוצות רכישה למה זה טוב ומה הסיכונים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/קבוצות-רכישה-למה-זה-טוב-ומה-הסיכונים/'],
      needsReview: true,
    },
    {
      slug: 'פנג-שואי-מה-חשוב-לשים-לב',
      kind: 'blog',
      title: 'פנג שואי (מה חשוב לשים לב) ולמה זה חשוב לאנרגיות בבית',
      excerpt: 'פנג שואי (מה חשוב לשים לב) ולמה זה חשוב לאנרגיות בבית',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/פנג-שואי-מה-חשוב-לשים-לב-ולמה-זה-חשוב-לא/'],
      needsReview: true,
    },
    {
      slug: 'מוכר-דירה',
      kind: 'blog',
      title: 'מוכר דירה? איך לעצב את הדירה בכלום כסף שתיראה לקונים מיליון דולר',
      excerpt: 'מוכר דירה? איך לעצב את הדירה בכלום כסף שתיראה לקונים מיליון דולר',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/מוכר-דירה-איך-לעצב-את-הדירה-בכלום-כסף-ש/'],
      needsReview: true,
    },
    {
      slug: 'מה-הם-הטיפים-לבחירת-בעל-מקצוע',
      kind: 'blog',
      title: 'מה הם הטיפים לבחירת בעל מקצוע',
      excerpt: 'מה הם הטיפים לבחירת בעל מקצוע',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/מה-הם-הטיפים-לבחירת-בעל-מקצוע/'],
      needsReview: true,
    },
    {
      slug: 'למה-פרויקטים-של-תמא-38-אינם',
      kind: 'blog',
      title: 'למה פרויקטים של תמ"א 38 אינם מתרוממים',
      excerpt: 'למה פרויקטים של תמ"א 38 אינם מתרוממים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/למה-פרויקטים-של-תמא-38-אינם-מתרוממים/'],
      needsReview: true,
    },
    {
      slug: 'חברה-מומלצת-לניהול-נכסים-ודירות-בהרצליה',
      kind: 'blog',
      title: 'חברה מומלצת לניהול נכסים ודירות בהרצליה זה קיסר ניהול נכסים',
      excerpt: 'חברה מומלצת לניהול נכסים ודירות בהרצליה זה קיסר ניהול נכסים',
      publishedAt: PENDING_DATE,
      legacyPaths: ['/httpwww-caesar-co-ilproperty_locationהשרון-והסביבהheaderanchor/'],
      needsReview: true,
    },
  ],
  'post',
);

/** True once the client's real publication date has replaced the sentinel. */
export function hasRealDate(post: Post): boolean {
  return post.publishedAt !== PENDING_DATE;
}

/** True once a real teaser has replaced the title-as-excerpt convention. */
export function hasRealExcerpt(post: Post): boolean {
  return post.excerpt !== post.title;
}

export const blogPosts: Post[] = posts.filter((post) => post.kind === 'blog');
export const newsPosts: Post[] = posts.filter((post) => post.kind === 'news');

export function postPath(post: Pick<Post, 'kind' | 'slug'>): string {
  return `/${post.kind}/${post.slug}`;
}

export function getPost(kind: Post['kind'], slug: string): Post | undefined {
  return posts.find((post) => post.kind === kind && post.slug === slug);
}
