/**
 * Bakes Hebrew font data into `lib/generated/og-font.ts` for the OG image route.
 *
 * Why baked rather than loaded at runtime:
 *   - Satori (behind next/og) cannot read WOFF2, only TTF/OTF/WOFF.
 *   - Google Fonts is unreachable from this environment.
 *   - Reading from node_modules at runtime is unreliable inside a bundler —
 *     Turbopack rewrites `require.resolve` to a numeric module id, and a
 *     serverless bundle may not trace node_modules assets at all.
 *
 * Why the STATIC family (@fontsource/heebo) and not the variable one the site
 * itself uses (@fontsource-variable/heebo): satori's font parser cannot read a
 * variable font — it throws `Cannot read properties of undefined (reading
 * '258')` on the wght axis. Static instances parse fine. The site keeps the
 * variable font; only the OG renderer uses these static cuts.
 *
 * WOFF is embedded as-is; no decompression step, so no wawoff2 at build time
 * either. ~44 KB of base64 total, in the OG route's chunk only.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require_ = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(root, 'lib/generated/og-font.ts');

/** Hebrew carries the copy; Latin carries digits, punctuation and Latin runs. */
const CUTS = [
  { name: 'hebrew400', file: 'heebo-hebrew-400-normal.woff' },
  { name: 'hebrew700', file: 'heebo-hebrew-700-normal.woff' },
  { name: 'latin400', file: 'heebo-latin-400-normal.woff' },
  { name: 'latin700', file: 'heebo-latin-700-normal.woff' },
] as const;

async function main() {
  const pkgDir = path.dirname(require_.resolve('@fontsource/heebo/package.json'));

  const parts: string[] = [];
  let total = 0;
  for (const cut of CUTS) {
    const woff = await readFile(path.join(pkgDir, 'files', cut.file));
    total += woff.byteLength;
    parts.push(
      `/** ${cut.file} — ${woff.byteLength} bytes, WOFF. */\n` +
        `export const ${cut.name}Base64 =\n  '${woff.toString('base64')}';`,
    );
  }

  await mkdir(path.dirname(OUT), { recursive: true });
  await writeFile(
    OUT,
    `/* eslint-disable */
/**
 * AUTOGENERATED — DO NOT EDIT BY HAND.
 *
 * Source:    node_modules/@fontsource/heebo/files/*.woff
 * Generator: scripts/gen-og-font.ts  (npm run gen:og-font)
 */

${parts.join('\n\n')}
`,
    'utf8',
  );
  console.log(`[gen:og-font] ${CUTS.length} cuts, ${total} B -> ${path.relative(root, OUT)}`);
}

main().catch((err) => {
  console.error('[gen:og-font] failed:', err);
  process.exit(1);
});
