/**
 * Generates `lib/content.types.ts` from `contracts/content.schema.json`.
 *
 * The schema is the single source of truth for the shape of `content/pages.json`.
 * Types are GENERATED from it rather than hand-written alongside it, so the two
 * can never drift. Runs automatically via the `prebuild` npm script.
 *
 * Note: JSON Schema conditionals (`if`/`then`, e.g. "a video must have a poster")
 * cannot be expressed as static TypeScript here, so they are enforced at runtime
 * by Ajv in `lib/content.ts`. The generated types are the structural half of the
 * contract; Ajv is the complete half.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { compile, type JSONSchema } from 'json-schema-to-typescript';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SCHEMA = path.join(root, 'contracts/content.schema.json');
const OUT = path.join(root, 'lib/content.types.ts');

const BANNER = `/* eslint-disable */
/**
 * AUTOGENERATED — DO NOT EDIT BY HAND.
 *
 * Source:    contracts/content.schema.json
 * Generator: scripts/gen-content-types.ts  (npm run gen:types)
 *
 * Edit the schema, then re-run \`npm run gen:types\`. \`npm run build\` does this
 * for you via \`prebuild\`.
 */
`;

/**
 * json-schema-to-typescript emits `{ [k: string]: unknown } & { ... }` for any
 * object that pairs `additionalProperties: false` with a top-level `allOf`
 * (our `media` and `provenance` defs do, to express the if/then rules). The
 * index signature is an artefact of that emit, not of the schema — the schema
 * genuinely forbids extra properties — so it is stripped here. Also exports a
 * `SiteContent` alias for the root type.
 */
function postProcess(ts: string): string {
  const cleaned = ts.replace(/\{\s*\[k: string\]: unknown;\s*\} & \{/g, '{');
  return `${cleaned}
/** Root type of content/pages.json. Alias for the schema's title-derived name. */
export type SiteContent = CaesarSiteContent;
`;
}

async function main() {
  const schema = JSON.parse(await readFile(SCHEMA, 'utf8')) as JSONSchema;

  const ts = await compile(schema, 'SiteContent', {
    additionalProperties: false,
    bannerComment: BANNER,
    declareExternallyReferenced: true,
    enableConstEnums: false,
    style: { singleQuote: true, printWidth: 100, semi: true },
    unreachableDefinitions: true,
  });

  await writeFile(OUT, postProcess(ts), 'utf8');
  console.log(`[gen:types] ${path.relative(root, SCHEMA)} -> ${path.relative(root, OUT)}`);
}

main().catch((err) => {
  console.error('[gen:types] failed:', err);
  process.exit(1);
});
